version: "3"
services:
  client:
    container_name: covid-dash-client
    build: ./client
    restart: always
    ports:
      - "80:3000"
    stdin_open: true

  api:
    container_name: covid-dash-api
    build: ./api
    ports:
      - "3000:3000"
